### ISSUE TITLE
installation error on Apple-M2

### ISSUE THREAD

**Issue by marabgol** [kadirnar/whisper-plus#112]
when I run on MacBook. Pro ( M2) I see this error:
pip install flash-attn --no-build-isolation
Collecting flash-attn
Downloading flash_attn-2.5.9.post1.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /private/var/folders/8b/w93rvnr56l9ggrhnmd9_fxg40000gn/T/pip-install-lnkc6862/flash-attn_e1b53d513277403db3953e1f96a235d2/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8b/w93rvnr56l9ggrhnmd9_fxg40000gn/T/pip-install-lnkc6862/flash-attn_e1b53d513277403db3953e1f96a235d2/setup.py", line 134, in <module>
          CUDAExtension(
        File "/opt/homebrew/anaconda3/envs/wishper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/wishper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/envs/wishper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

      torch.__version__  = 2.3.1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kadirnar** [comment]
Mac devices don't support flash-att.

For Mac devices, you can try this:
https://github.com/kadirnar/whisper-plus?tab=readme-ov-file#-apple-mlx
