### ISSUE TITLE
macOS dependencies for lightning-whisper-mlx

### ISSUE THREAD

**Issue by fhaer** [kadirnar/whisper-plus#117]
Hello,

Thank you for such a great tool that integrates several high-performance libraries and extra features.

Possibly it is clear, however, I missed how to configure a specific model such as large-v3 and how to use it with lightning-whisper-mlx.

Steps taken:
```
python3.11 -m venv venv
source venv/bin/activate
pip3.11 install git+https://github.com/kadirnar/whisper-plus.git
pip3.11 install git+https://github.com/huggingface/transformers
pip3.11 install lightning-whisper-mlx
```

Then executing the demo code from readme.md:
```
source venv/bin/activate
python3.11 run.py
```

run.py:
```
from whisperplus.pipelines.lightning_whisper_mlx import LightningWhisperMLX
from whisperplus import download_youtube_to_mp3

url = "https://www.youtube.com/watch?v=1__CAdTJ5JU"
audio_path = download_youtube_to_mp3(url)

whisper = LightningWhisperMLX(model="distil-large-v3", batch_size=12, quant=None)
output = whisper.transcribe(audio_path=audio_path)["text"]
```

Error:
```
Traceback (most recent call last):
  File "/Users/u/ws/whisperplus/transcribe-yt.py", line 1, in <module>
    from whisperplus.pipelines.lightning_whisper_mlx import LightningWhisperMLX
  File "/Users/u/ws/whisperplus/venv/lib/python3.11/site-packages/whisperplus/__init__.py", line 5, in <module>
    from whisperplus.pipelines.whisper import SpeechToTextPipeline
  File "/Users/u/ws/whisperplus/venv/lib/python3.11/site-packages/whisperplus/pipelines/whisper.py", line 6, in <module>
    from whisperplus.model.load_model import load_model_whisper
ModuleNotFoundError: No module named 'whisperplus.model'
```

Thank you, best 

Felix

**Comment by kadirnar** [comment]
Thank you for the feedback. I will solve it today.
