### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by theandrepo** [kadirnar/whisper-plus#119]
I am using:

WhisperPlus v0.3.0
Cuda 12.1
It throws the following error : 

```
Traceback (most recent call last):
  File "D:\02-GENAI\whisper-plus\App_Diarization.py", line 17, in <module>
    output_text = pipeline(audio_path, num_speakers=2, min_speaker=1, max_speaker=2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\02-GENAI\whisper-plus\whisperplus\pipelines\whisper_diarize.py", line 171, in __call__
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
                                ~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```
When I use this request (aligned with repo instructions)....

```
from whisperplus.pipelines.whisper_diarize import ASRDiarizationPipeline
from whisperplus import download_youtube_to_mp3, format_speech_to_dialogue

audio_path = download_youtube_to_mp3("https://www.youtube.com/watch?v=3p-VBQ4l-4s") 

device = "cuda"  # cuda / cpu / mps
pipeline = ASRDiarizationPipeline.from_pretrained(
    asr_model="openai/whisper-large-v3",
    diarizer_model="pyannote/speaker-diarization-3.1",
    #use_auth_token=False,
    use_auth_token="here_comes_my_token",
    chunk_length_s=30,
    device=device,
)
output_text = pipeline(audio_path, num_speakers=2, min_speaker=1, max_speaker=2)
dialogue = format_speech_to_dialogue(output_text)
print(dialogue)
```

Any idea ?

**Comment by kadirnar** [comment]
Didn't download the mp3 file. Is the link correct?

**Comment by IzzyHibbert** [comment]
> Didn't download the mp3 file. Is the link correct?

Yes, works. Even a copy+paste in browser works for me.

**Comment by kadirnar** [comment]
Sometimes there is a problem while downloading. That's why you have to try again and again.

**Comment by IzzyHibbert** [comment]
> Sometimes there is a problem while downloading. That's why you have to try again and again.

No I had my file downloaded. The error occurs after, you can see that it fails in the speakers line

whisper_diarize.py

line 171

**Comment by IzzyHibbert** [comment]
Also, I made another video to work, using CPU, same machine (sonot an issue with the installation to me)

**Comment by kadirnar** [comment]
Can you give the path of the .mp3 file to the audio_pah variable? Because it cannot read the audio file. It returns to None.

**Comment by IzzyHibbert** [comment]
> Can you give the path of the .mp3 file to the audio_pah variable? Because it cannot read the audio file. It returns to None.

I will try early tomorrow and let you know, thanks

**Comment by IzzyHibbert** [comment]
Ok, I founded out.
It turned that the solution is not able to process the video (audio) I used :

https://www.youtube.com/watch?v=3p-VBQ4l-4s

I tried both with CUDA and CPU. Both KO. As soon as in the same installation I use another video (audio) it works fine.

My 2cents: the only possible cause I see for this case is a bug when the video (audio) includes few notes of a jingle at the beginning of the audio and no voices (which just come seconds after..

**Comment by risedangel** [comment]
To my opinion this occurs when the code cannot produce an  `"end": cur_segment["segment"]["end"]` to the audio, hence  `end_time = segment["segment"]["end"]` becomes "NoneType" and results with the given error

**Comment by GuyPaddock** [comment]
Also seeing this, and @risedangel seems to be correct:
```
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
Traceback (most recent call last):
  File "/mnt/array1/home/guyep/playground/whisper-plus/diarize.py", line 18, in <module>
    output_text = pipeline(audio_path, num_speakers=16)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/array1/home/guyep/miniconda3/envs/whisper-plus/lib/python3.12/site-packages/whisperplus/pipelines/whisper_diarize.py", line 171, in __call__
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
                                ~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by maxnadig** [comment]
I do still have the same issue, the audio file itself seems fine, it can be used for transcription without the diarization.
Did you find a workauround for this @IzzyHibbert ?

**Comment by risedangel** [comment]
I seem to work it around by cutting the file  after a meaningfull word because i seem to have this problem only when the last word is not completed in the audio

**Comment by maxnadig** [comment]
I was not able to make it happen. It's a pretty quick phone conversations, sometimes with two people speaking simultaniously.
I'd assume that the diarization will end up creating audio snippets automatically, thus leading to faulty ones. Maybe just a plain fix of the error in the code would already be enough? Or do we need those timestamps to be calculated?
