### ISSUE TITLE
ValueError: We expect a numpy ndarray as input, got `<class 'NoneType'>`

### ISSUE THREAD

**Issue by fEyebrow** [kadirnar/whisper-plus#29]
I  followed the steps of "Youtube URL to Audio", but the following error occurred:
```
2023-12-18 11:06:54,971 - INFO - Transcribing audio...
Traceback (most recent call last):
  File "/Users/jinlin/Desktop/learn/whisperplus/index.py", line 11, in <module>
    transcript = pipeline(
                 ^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/whisperplus/pipelines/whisper.py", line 74, in __call__
    result = pipe(audio_path)["text"]
             ^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/base.py", line 1132, in __call__
    return next(
           ^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/pt_utils.py", line 183, in __next__
    processed = next(self.subiterator)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jinlin/Desktop/learn/whisperplus/lib/python3.11/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 482, in preprocess
    raise ValueError(f"We expect a numpy ndarray as input, got `{type(inputs)}`")
ValueError: We expect a numpy ndarray as input, got `<class 'NoneType'>`
```
Here is my config of env:
home = /opt/homebrew/opt/python@3.11/bin
include-system-site-packages = false
version = 3.11.4
executable = /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
command = /opt/homebrew/opt/python@3.11/bin/python3.11 -m venv /Users/jinlin/Desktop/learn/whisperplus

**Comment by kadirnar** [comment]
Can you share your code?

**Comment by denissa4** [comment]
Same issue for my test on MacOS M2, Python 3.10
Code is same as readme file sample: 
```
from whisperplus import SpeechToTextPipeline, download_and_convert_to_mp3

# Define the URL of the YouTube video that you want to convert to text.
url = "https://www.youtube.com/watch?v=di3rHkEZuUw"

# Initialize the Speech to Text Pipeline with the specified model.
audio_path = download_and_convert_to_mp3(url)
pipeline = SpeechToTextPipeline(model_id="openai/whisper-large-v3")

# Run the pipeline on the audio file.
transcript = pipeline(
    audio_path=audio_path, model_id="openai/whisper-large-v3", language="english"
)

# Print the transcript of the audio.
print(transcript)
```

Thank you for your work!

**Comment by kadirnar** [comment]
> Same issue for my test on MacOS M2, Python 3.10 Code is same as readme file sample:
> 
> ```
> from whisperplus import SpeechToTextPipeline, download_and_convert_to_mp3
> 
> # Define the URL of the YouTube video that you want to convert to text.
> url = "https://www.youtube.com/watch?v=di3rHkEZuUw"
> 
> # Initialize the Speech to Text Pipeline with the specified model.
> audio_path = download_and_convert_to_mp3(url)
> pipeline = SpeechToTextPipeline(model_id="openai/whisper-large-v3")
> 
> # Run the pipeline on the audio file.
> transcript = pipeline(
>     audio_path=audio_path, model_id="openai/whisper-large-v3", language="english"
> )
> 
> # Print the transcript of the audio.
> print(transcript)
> ```
> 
> Thank you for your work!
It works for me too. How did you do the installation?
<img width="1678" alt="image" src="https://github.com/kadirnar/whisper-plus/assets/36204372/f65a279d-9c61-4934-b40e-ea93a7b5a624">

**Comment by kadirnar** [comment]
Mac:

<img width="910" alt="image" src="https://github.com/kadirnar/whisper-plus/assets/36204372/b1645ad3-15d0-41c3-8b71-b720beb5cf3a">

**Comment by kadirnar** [comment]
https://huggingface.co/spaces/ArtGAN/Audio-WebUI

You can try this demo.

**Comment by rohitkrishna094** [comment]
@fEyebrow were you able to figure the underlying issue? I am getting the same error on google colab. There is some inherent issue in this repo's codebase, switching to different provider might not work for all.
