### ISSUE TITLE
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

### ISSUE THREAD

**Issue by carlosalberto2000** [kadirnar/whisper-plus#58]
Hello.
I'm trying to run Whisper Plus but keep getting this error message:
```
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
``` 

Using the example code (Youtube URL to Audio):
```python
from whisperplus import SpeechToTextPipeline, download_and_convert_to_mp3

url = "https://www.youtube.com/watch?v=di3rHkEZuUw"

audio_path = download_and_convert_to_mp3(url)
pipeline = SpeechToTextPipeline(model_id="distil-whisper/distil-large-v2")
transcript = pipeline(audio_path, "distil-whisper/distil-large-v2", "english")

print(transcript)
``` 

I created a new environment with Miniconda (with Python 3.11 on Windows 10) called "whisper", then -> ```conda activate whisper``` -> ```pip install whisperplus``` -> ```y``` -> (Run the code above at VS Code with the correct environment selected) -> Error "ffmpeg" not located -> ```pip install ffmpeg``` -> (Run) -> Error "ffmpeg" not located -> ```pip uninstall ffmpeg``` -> ```conda install conda-forge::ffmpeg``` -> (Run) -> RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

Checked the "requirements.txt" and everything is installed accordingly.

Trying to run the AutoCaption code gets a "ImportError: cannot import name 'WhisperAutoCaptionPipeline' from 'whisperplus' (C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\whisperplus\__init__.py)".

I don't know what is going on!
Any insight would be greatly appreciated!
Thanks!!!

Full error:
```
C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher 
enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch_audiomentations\utils\io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
2024-02-05 00:55:52,780 - INFO - Downloading started... output\test.mp3
2024-02-05 00:55:55,000 - INFO - Download and conversion successful. File saved at: output\test.mp3
2024-02-05 00:55:55,000 - INFO - Loading model...
2024-02-05 00:55:55,959 - INFO - Model loaded successfully.
2024-02-05 00:55:55,959 - INFO - Using device: cpu
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-02-05 00:55:56,886 - INFO - Transcribing audio...
Traceback (most recent call last):
  File "c:\Users\Daniel\Videos\Work Work\import os.py", line 7, in <module>
    transcript = pipeline(audio_path, "distil-whisper/distil-large-v2", "english")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\whisperplus\pipelines\whisper.py", line 74, in __call__
    result = pipe(audio_path)["text"]
             ^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\base.py", line 1132, in __call__
    return next(
           ^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 555, in _forward
    encoder_outputs=encoder(inputs, attention_mask=attention_mask),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\models\whisper\modeling_whisper.py", line 1119, in forward
    inputs_embeds = nn.functional.gelu(self.conv1(input_features))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```

**Comment by carlosalberto2000** [comment]
CUDA was not detecting my GPU.
Sorry for my newbie mistake!

Solved by:
```conda install pytorch torchvision torchaudio cudatoolkit -c pytorch -c nvidia``` -> ```pip install chardet``` 

Now, Youtube URL to Audio example code works!
This will help immensely my studies, thank you so much!


AutoCaption unfortunately still does not.
I noticed the PIP package is an older version of this repo, that is why it was getting an ImportError.
After updating the files and adding ```from whisperplus.pipelines.whisper_autocaption import WhisperAutoCaptionPipeline``` to the root ```__init__.py```, it ran, but always gives this error:

```RuntimeError: Given groups=1, weight of size [1280, 80, 3], expected input[7, 128, 3000] to have 80 channels, but got 128 channels instead```

Full error:
```
INFO:root:Loading model...
INFO:root:Model loaded successfully.
INFO:root:Using device: cuda
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with clang version 17.0.6
  configuration: --prefix=/d/bld/ffmpeg_1706918581257/_h_env/Library --cc=clang.exe --cxx=clang++.exe --nm=llvm-nm --ar=llvm-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --ld=lld-link --target-os=win64 --enable-cross-compile --toolchain=msvc --host-cc=clang.exe --extra-libs=ucrt.lib --extra-libs=vcruntime.lib --extra-libs=oldnames.lib --strip=llvm-strip --disable-stripping --host-extralibs= --disable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus 
--pkg-config=/d/bld/ffmpeg_1706918581257/_build_env/Library/bin/pkg-config
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:02:25.24, start: 0.000000, bitrate: 567 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 430 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> mp3 (mp3_mf))
Press [q] to stop, [?] for help
[mp3_mf @ 00000115FDE70780] MFT name: 'MP3 Encoder ACM Wrapper MFT'
Output #0, mp3, to 'test.mp3':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    TSSE            : Lavf60.16.100
  Stream #0:0(und): Audio: mp3, 48000 Hz, stereo, s16, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 mp3_mf
[out#0/mp3 @ 00000115FC37F840] video:0kB audio:2270kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.022884%
size=    2271kB time=00:02:25.23 bitrate= 128.1kbits/s speed= 199x
INFO:root:Transcribing audio...
preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 340/340 [00:00<?, ?B/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 283k/283k [00:00<00:00, 2.11MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 2.85MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.48M/2.48M [00:00<00:00, 9.36MB/s]
merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 494k/494k [00:00<00:00, 2.16MB/s]
normalizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.7k/52.7k [00:00<00:00, 26.3MB/s]
added_tokens.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.6k/34.6k [00:00<00:00, 304kB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.07k/2.07k [00:00<?, ?B/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "c:\Users\Daniel\Videos\Work Work\import os.py", line 14, in <module>
    caption(video_path="test.mp4", output_path="output.mp4", language="english")
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\whisperplus\pipelines\whisper_autocaption.py", line 87, in __call__
    result = pipe(audio_path)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\base.py", line 1132, in __call__
    return next(
           ^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 555, in _forward
    encoder_outputs=encoder(inputs, attention_mask=attention_mask),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\transformers\models\whisper\modeling_whisper.py", line 1119, in forward
    inputs_embeds = nn.functional.gelu(self.conv1(input_features))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\miniconda3\envs\whisper\Lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [1280, 80, 3], expected input[7, 128, 3000] to have 80 channels, but got 128 channels instead
```

**Comment by kadirnar** [comment]
Thanks ❤️
